name: Setup Salt
author: dafyddj
description: Install and set up Salt on Windows
inputs:
  salt-version:
    description: Version of Salt to install
    required: false
    default: latest
  file-client:
    description: Set `file_client` parameter
    required: false
    default: local
  custom-config:
    description: Add a custom minion config
    required: false
  timeout-seconds:
    description: The maximum number of seconds to allow the Salt installation to run for
    required: false
    default: 180
runs:
  using: composite
  steps:
    - name: Set `file_client`
      shell: bash
      working-directory: ${{ runner.temp }}
      run: |
        echo "file_client: ${{ inputs.file-client }}" >config
    - name: Set custom config
      shell: bash
      working-directory: ${{ runner.temp }}
      run: |
        if [ -n "${{ inputs.custom-config }}" ]; then
            echo -n "${{ inputs.custom-config }}" >>config
        fi
    - name: Run Salt installer
      shell: pwsh
      working-directory: ${{ runner.temp }}
      run: |
        $version = "${{ inputs.salt-version }}"

        $rcDir = $version.Contains("rc") ? "salt_rc/" : ""
        $repoDomain = "packages.broadcom.com"

        $simpleVersion = $version -replace '(\d+\.\d+)rc\d+', '$1'
        if ([version]$simpleVersion -ge [version]"3006.0") {
            $repoDir = "artifactory/saltproject-generic/windows/${version}"
        } elseif ([version]$simpleVersion -eq [version]"3005.5") {
            $repoDomain = "www.dropbox.com"
            $repoDir = "scl/fi/c9526kgslr7qgfl6gllgj"
            $params = "?rlkey=zj1ztrsjjmzuna6rslnv35ski&st=pk1dudf3&dl=1"
        } else {
            Write-Host ("::error title=Setup Salt installation::Versions before v3005.5 are NOT supported")
            exit 1
        }

        Invoke-WebRequest `
          -Uri https://${repoDomain}/${repoDir}/Salt-Minion-${version}-Py3-AMD64-Setup.exe${params} `
          -OutFile salt.exe

        # The installer returns to the command line immediately after launch
        # when run without `-Wait` or assigning to a $process variable
        $process = Start-Process -PassThru salt.exe -ArgumentList `
          /S,/custom-config=config

        $timeout = ${{ inputs.timeout-seconds }}

        if (!$process.WaitForExit(1000 * $timeout)) {
          $process | Stop-Process
          Write-Host ("::error title=Setup Salt installation::Installation timed out and was terminated")
          exit 1
        }

        if ([version]$simpleVersion -ge [version]"3004.0") {
            $saltPath = "C:\Program Files\Salt Project\Salt"
        } else {
            $saltPath = "C:\salt"
        }
        $saltPath | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

        # Enable embedded quotes on next invocation of `pwsh`
        # Mainstreamed in `7.3.0`
        if ($PSVersionTable.PSVersion -lt [version]"7.3.0") {
            Enable-ExperimentalFeature PSNativeCommandArgumentPassing
        }
    - name: Test Salt installation
      shell: pwsh
      run: |
        function Test-LastExitCode {
            param ([int]$lec)
            if ($lec) {
                Write-Host ("::error title=Test Salt installation::Native process returned exit code: $lec")
                exit 1
            }
        }
        $pkgsJson = salt-call --out=json pkg.list_pkgs
        Test-LastExitCode($LASTEXITCODE)
        $pkgsJson | jq 'to_entries|map(.value|with_entries(if (.key|test("Salt Minion")) then ({key: .key, value: .value}) else empty end))'
        Test-LastExitCode($LASTEXITCODE)
