name: Setup Salt
author: dafyddj
description: Install and set up Salt on Windows
inputs:
  version:
    description: Version of Salt to install
    required: false
    default: latest
runs:
  using: composite
  steps:
    - shell: pwsh
      working-directory: ${{ runner.temp }}
      run: |
        Invoke-WebRequest -Uri https://winbootstrap.saltproject.io -OutFile bootstrap-salt.ps1
        & .\bootstrap-salt.ps1 -runservice false -version ${{ inputs.version }}
        if ([version]"${{ inputs.version }}.0" -ge [version]"3004.0") {
            $saltPath = "C:\Program Files\Salt Project\Salt"
        } else {
            $saltPath = "C:\salt"
        }
        $saltPath | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
