---
name: Main
on:
  push:
  pull_request:
  schedule:
    - cron: 14 15 * * *

jobs:
  pre-commit:
    name: Run `pre-commit`
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.3
  gsv:
    name: Get Salt versions
    runs-on: ubuntu-latest
    outputs:
      salt-versions: ${{ steps.get-salt-versions.outputs.salt-versions }}
    steps:
      - id: get-salt-versions
        uses: dafyddj/get-salt-versions@v2
  test:
    name: Test this action
    needs: gsv
    runs-on: windows-latest
    strategy:
      matrix:
        salt-version: ${{ fromJSON(needs.gsv.outputs.salt-versions) }}
    steps:
      - uses: actions/checkout@v2
      - name: Run this action
        uses: ./
        with:
          salt-version: ${{ matrix.salt-version }}
          custom-config: |
            test_key1: test_value1
            test_key2: test_value2
      - name: Verify Salt version installed
        env:
          SALT_VER_EXPECTED: ${{ matrix.salt-version }}
        run: |
          $SALT_VER_INSTALLED = (-split $(salt-call --version))[1]
          if ($SALT_VER_INSTALLED -ne $env:SALT_VER_EXPECTED) {
              exit 1
          }
      - name: Verify custom config
        run: |
          foreach ($i in 1..2) {
              $value = salt-call config.get "test_key$i" --out newline_values_only
              if ($value -ne "test_value$i") {
                  exit 1
              }
          }
  release:
    name: Release
    needs:
      - pre-commit
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run `semantic-release`
        uses: codfish/semantic-release-action@v1
        id: sem-rel
        with:
          branches: |
            ["main"]
          plugins: |
            [ "@semantic-release/commit-analyzer",
              "@semantic-release/release-notes-generator",
              "@semantic-release/github"
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update branch for major version
        if: steps.sem-rel.outputs.new-release-published == 'true'
        run: git push
             https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
             HEAD:refs/heads/v${{steps.sem-rel.outputs.release-major}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
